DROP TABLE IF EXISTS `TABLE-NAME`;
CREATE TABLE `TABLE-NAME` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `server_id` int(10) UNSIGNED NOT NULL,
  `meeting_id` int(10) UNSIGNED NOT NULL,
  `organization_key` varchar(32) COLLATE utf8_bin DEFAULT NULL,
  `name` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `time_zone` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `weekday` tinyint(3) UNSIGNED DEFAULT NULL,
  `single_occurrence_date` datetime DEFAULT NULL,
  `duration` int(10) UNSIGNED DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `latitude` float DEFAULT NULL,
  `tag0` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `tag1` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `tag2` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `tag3` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `tag4` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `tag5` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `tag6` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `tag7` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `tag8` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `tag9` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `comments` text COLLATE utf8_bin,
  `formats` text COLLATE utf8_bin,
  `physical_address` text COLLATE utf8_bin DEFAULT NULL,
  `virtual_information` text COLLATE utf8_bin DEFAULT NULL,
  `last_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ALTER TABLE `TABLE-NAME`
  ADD PRIMARY KEY (`id`),
  ADD KEY `server_id` (`server_id`),
  ADD KEY `meeting_id` (`meeting_id`),
  ADD KEY `organization_key` (`organization_key`),
  ADD KEY `name` (`name`),
  ADD KEY `start_time` (`start_time`),
  ADD KEY `time_zone` (`time_zone`),
  ADD KEY `weekday` (`weekday`),
  ADD KEY `single_occurrence_date` (`single_occurrence_date`),
  ADD KEY `duration` (`duration`),
  ADD KEY `longitude` (`longitude`),
  ADD KEY `latitude` (`latitude`),
  ADD KEY `tag0` (`tag0`),
  ADD KEY `tag1` (`tag1`),
  ADD KEY `tag2` (`tag2`),
  ADD KEY `tag3` (`tag3`),
  ADD KEY `tag4` (`tag4`),
  ADD KEY `tag5` (`tag5`),
  ADD KEY `tag6` (`tag6`),
  ADD KEY `tag7` (`tag7`),
  ADD KEY `tag8` (`tag8`),
  ADD KEY `tag9` (`tag9`);
ALTER TABLE `TABLE-NAME`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;
